-- Find total customers by countries
SELECT
country,
count(customer_number) total_customers
FROM gold.dim_customers
GROUP BY country
order by total_customers DESC

-- Find total customers by gender
SELECT 
gender, 
count(customer_number) total_customers
FROM gold.dim_customers
GROUP BY gender
order by total_customers DESC

--Find total products by Category
select 
category,
count(distinct product_id) total_products
FROM gold.dim_products
GROUP BY category
order by total_products DESC

-- What is the average cost in each category
select 
category,
avg(cost) avg_cost
FROM gold.dim_products
GROUP BY category
order by avg_cost DESC

-- What is the most running item in each category
select 
p.category,
sum(quantity) total_quantity
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY p.category
order by total_quantity DESC

--What is the total revenue generated for each category
SELECT 
p.category,
sum(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY p.category
order by total_revenue DESC

--What is the total revenue generated by each customer
select 
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) AS total_purchase,
COUNT(s.customer_key) AS total_orders
FROM gold.fact_sales  s
LEFT JOIN gold.dim_customers c ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
order by total_purchase DESC


select * from gold.fact_sales 
select * from gold.dim_products
select * from gold.dim_customers

--what is the distibution of sold items accross countries
select 
c.country,
SUM(sales_amount) AS total_purchase,
COUNT(s.customer_key) AS total_sold_items
FROM gold.fact_sales  s
LEFT JOIN gold.dim_customers c ON c.customer_key = s.customer_key
GROUP BY 
	c.country
order by total_purchase DESC
